// Code generated by protoc-gen-go. DO NOT EDIT.
// source: full.proto

package full

import (
	fmt "fmt"
	math "math"

	"github.com/golang/protobuf/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionedStatusArgs struct {
	MinVersion           int32    `protobuf:"varint,10,opt,name=MinVersion,proto3" json:"MinVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionedStatusArgs) Reset()         { *m = VersionedStatusArgs{} }
func (m *VersionedStatusArgs) String() string { return proto.CompactTextString(m) }
func (*VersionedStatusArgs) ProtoMessage()    {}
func (*VersionedStatusArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbc2e675beec816d, []int{0}
}

func (m *VersionedStatusArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionedStatusArgs.Unmarshal(m, b)
}
func (m *VersionedStatusArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionedStatusArgs.Marshal(b, m, deterministic)
}
func (m *VersionedStatusArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionedStatusArgs.Merge(m, src)
}
func (m *VersionedStatusArgs) XXX_Size() int {
	return xxx_messageInfo_VersionedStatusArgs.Size(m)
}
func (m *VersionedStatusArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionedStatusArgs.DiscardUnknown(m)
}

var xxx_messageInfo_VersionedStatusArgs proto.InternalMessageInfo

func (m *VersionedStatusArgs) GetMinVersion() int32 {
	if m != nil {
		return m.MinVersion
	}
	return 0
}

type StatusArgs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusArgs) Reset()         { *m = StatusArgs{} }
func (m *StatusArgs) String() string { return proto.CompactTextString(m) }
func (*StatusArgs) ProtoMessage()    {}
func (*StatusArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbc2e675beec816d, []int{1}
}

func (m *StatusArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusArgs.Unmarshal(m, b)
}
func (m *StatusArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusArgs.Marshal(b, m, deterministic)
}
func (m *StatusArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusArgs.Merge(m, src)
}
func (m *StatusArgs) XXX_Size() int {
	return xxx_messageInfo_StatusArgs.Size(m)
}
func (m *StatusArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusArgs.DiscardUnknown(m)
}

var xxx_messageInfo_StatusArgs proto.InternalMessageInfo

type StatusResponse struct {
	Version              int64    `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	GitRef               string   `protobuf:"bytes,11,opt,name=gitRef,proto3" json:"gitRef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbc2e675beec816d, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StatusResponse) GetGitRef() string {
	if m != nil {
		return m.GitRef
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionedStatusArgs)(nil), "full.VersionedStatusArgs")
	proto.RegisterType((*StatusArgs)(nil), "full.StatusArgs")
	proto.RegisterType((*StatusResponse)(nil), "full.StatusResponse")
}

func init() { proto.RegisterFile("full.proto", fileDescriptor_bbc2e675beec816d) }

var fileDescriptor_bbc2e675beec816d = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2b, 0xcd, 0xc9,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x4c, 0xb9, 0x84, 0xc3, 0x52,
	0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0x52, 0x53, 0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x1d, 0x8b, 0xd2,
	0x8b, 0x85, 0xe4, 0xb8, 0xb8, 0x7c, 0x33, 0xf3, 0xa0, 0x32, 0x12, 0x5c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x48, 0x22, 0x4a, 0x3c, 0x5c, 0x5c, 0x08, 0xd5, 0x4a, 0x4e, 0x5c, 0x7c, 0x10, 0x5e, 0x50,
	0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x19, 0x92, 0x66, 0xe6, 0x20,
	0x18, 0x57, 0x48, 0x8c, 0x8b, 0x2d, 0x3d, 0xb3, 0x24, 0x28, 0x35, 0x4d, 0x82, 0x5b, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xca, 0x33, 0x72, 0xe5, 0x62, 0x83, 0x98, 0x21, 0x64, 0x0d, 0x67, 0x49, 0xea,
	0x81, 0xdd, 0x8b, 0xc5, 0x81, 0x52, 0x22, 0x10, 0x29, 0x54, 0x6b, 0x95, 0x18, 0x92, 0xd8, 0xc0,
	0x9e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x9d, 0x10, 0x14, 0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatusClient is the client API for Status service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatusClient interface {
	Status(ctx context.Context, in *VersionedStatusArgs, opts ...grpc.CallOption) (*StatusResponse, error)
}

type statusClient struct {
	cc *grpc.ClientConn
}

func NewStatusClient(cc *grpc.ClientConn) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) Status(ctx context.Context, in *VersionedStatusArgs, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/full.Status/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServer is the server API for Status service.
type StatusServer interface {
	Status(context.Context, *VersionedStatusArgs) (*StatusResponse, error)
}

func RegisterStatusServer(s *grpc.Server, srv StatusServer) {
	s.RegisterService(&_Status_serviceDesc, srv)
}

func _Status_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionedStatusArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/full.Status/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).Status(ctx, req.(*VersionedStatusArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Status_serviceDesc = grpc.ServiceDesc{
	ServiceName: "full.Status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Status_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "full.proto",
}
